# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72df685432ac071cd03a7760dd7f96f9ca67fe1f7c6527b8f662b5ca04d95690414e817c9e5fd56c4c19cc748cee97b203f6774f0889c91a7a6fb4abe74e522b

test:
  secret_key_base: 999e8b46227b85096717bda8bbc05dca085b97a7c7e6dcc373a063abfe0f7b2b2663f32071d87853364e7c848fe00d3b62054cc7f93872a21a099c19caaf6ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
